### ISSUE TITLE
Ability to add a "Slots" section in the item card

### ISSUE THREAD

**Issue by w1face** [Handyfon/Darksheet#1]
Is there the ability to add a "no of slots" field to the item cards?  This way we can edit existing items, or create custom items easier.

**Comment by Handyfon** [comment]
Slots already exist for items, you need to select "Darkitems" for the item sheet

**Comment by w1face** [comment]
Whilst this true... if I want to edit the slots an item takes up, I can't.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by nearlyNonexistent** [comment]
The request seems to be to be able to type in custom slots; which woul be very helpful.

**Comment by Handyfon** [comment]
done
