### ISSUE TITLE
Remove CSS

### ISSUE THREAD

**Issue by NutritiousCookie** [Handyfon/Darksheet#14]
So, eyebleed colors, weird overlays, !important tags on everything... its a mess.

I deleted darksheet.css which fixed it for me. Still, it's crazy that you made the css default. Put that stuff in another module if you really want to make it, the css for a character sheet should focus on compatibility.

**Comment by akrigline** [comment]
Alternatively, check out [Whetstone](https://github.com/MajorVictory/Whetstone) as an option to keep the CSS included in this module, but allow users to toggle it on and off.
