### ISSUE TITLE
Automatic Spell Burnout always rolls a d12

### ISSUE THREAD

**Issue by poppythompson** [Handyfon/Darksheet#20]
The dropdown menu changes to reflect the decrease in the burnout die, but the auto-roll always rolls a d12. This seems to only happen when it is rolling as a result of casting a spell. It operates normally when using the Burnout 'button'. But, when casting a spell, it reverts back to a d10 or d12.

**Comment by Handyfon** [comment]
Thank you for creating this issue, the problem will be fixed with the next update.
