### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by akrigline** [Handyfon/Darksheet#25]
Is there an open source license noted somewhere I am not finding for this repository? I'm interested in implementing similar but different mechanics into a different module and was hoping to get a head start by looking through what you've already written.

But if this code is [all rights reserved](https://choosealicense.com/no-permission/) (as implied by having no license, I don't think I should). I just wanted to double check about this.

**Comment by Handyfon** [comment]
First of all, thank you for asking.
You are welcome to use my code for your project. If you find my code helpful I would appreciate it if you mention me on your repository.

**Comment by akrigline** [comment]
I would greatly appreciate if a LICENSE file was implemented or made note of on the readme to clarify what restrictions/allowances you have in mind.

Here's some common ones in the Foundry VTT Community:
- [MIT](https://choosealicense.com/licenses/mit/)
- [GNU General Public License v3.0](https://choosealicense.com/licenses/gpl-3.0/)
- [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

Github makes this process pretty easy if you [use the web-UI](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

Thanks for clarifying!
