### ISSUE TITLE
Incompatable with Giffyglyph's Monster Maker Sheets

### ISSUE THREAD

**Issue by lorbog** [Handyfon/Darksheet#27]
When both this module and the official monster maker module are installed, items using the default 5e item sheet cannot be opened. (Gives the monster maker error screen). The items work normally when dark-sheet is disabled.

Suggestion: Make the darksheet items a separate item sheet type rather than changing the base sheet.

![image](https://user-images.githubusercontent.com/31111987/120903382-da0e9880-c613-11eb-8c13-3a7e735cf3e8.png)

**Comment by Handyfon** [comment]
this issue should be fixed
