### ISSUE TITLE
Update to new Foundry Version

### ISSUE THREAD

**Issue by Matsozetex** [Handyfon/Darksheet#28]
Just querying whether this will be updated to the new version of Foundry (0.8.6+)?

**Comment by Handyfon** [comment]
The update for 0.8.6+ will come in the next couple of days

**Comment by cbgh2021** [comment]
Sorry to be impatient, but has there been an update?

**Comment by subatoiWolf** [comment]
also curious love the mod but im on 8.8

**Comment by Handyfon** [comment]
Updated!
