### ISSUE TITLE
Chat Log is messed up with Module enabled.

### ISSUE THREAD

**Issue by giogreymon** [Handyfon/Darksheet#29]
With the module enabled, any rolls past the first recorded one is automatically deleted. This happens when rolling from DarkSheet and Default 5e sheet.

FVTT ver. 0.8.8
DnD5e ver. 1.3.6
Darksheet 5e ver. 3.2.0
No modules enabled other than Darksheet 5e

![unknown_2021 07 01-00 14](https://user-images.githubusercontent.com/77355668/124063684-6f2d6300-da01-11eb-9d59-c6c47585806e.gif)

**Comment by Handyfon** [comment]
Thank you for telling me, I pushed out a fix

**Comment by cbgh2021** [comment]
The fix didn't work.
Everything added to chat is quickly deleted.

**Comment by Handyfon** [comment]
Are you on Darksheet version 3.2,2?

**Comment by cbgh2021** [comment]
yes

**Comment by cbgh2021** [comment]
its a conflict with another module.

**Comment by cbgh2021** [comment]
DF Chat enhancements and it's dependant, library: chat enhancements

**Comment by giogreymon** [comment]
It works now, at least for core and other modules like midi and dae. I dont have DF Chat enhancements so I can't input on that
