### ISSUE TITLE
Wounds and Close Wounds doesn't work properly

### ISSUE THREAD

**Issue by giogreymon** [Handyfon/Darksheet#31]
When creating wounds, they can't be named, treated or deleted. It also doesnt recognize Closed Wounds, therefore not being able to close them.

I can take a gif later on to show it.

**Comment by subatoiWolf** [comment]
im also having this issue

**Comment by subatoiWolf** [comment]
really want to use your module it looks like it would be perfect for a campaign i am starting

**Comment by Handyfon** [comment]
Hey do you have any modules enabled that might conflict with Darksheet?

**Comment by Handyfon** [comment]
Incompatability with DAE fixed in new version
