### ISSUE TITLE
A lot of features on the Gamemaster Screen does not work

### ISSUE THREAD

**Issue by giogreymon** [Handyfon/Darksheet#33]
Things that DO work: Guide-check and Foraging checks seems to work fine. As well as changing the DCs based on the environment above.
Things that DONT work:
- Perception Rolls for Lookout and Scout; this is with core foundry, hopefully if you get to it it also works with Midi
- changing the Temperature or Regional Magic does not change it on the Players' sheets
- applying Hunger/Thirst/Fatigue doesn't work when you click the buttons for each phase of the day

lastly, it's not a pressing issue but it would be great if the travel pace can apply advantage/disadvantage on the rolls based on it. e.g at a normal Pace, everyone rolls normally but forage rolls at disadvantage; or at Fast Pace, everyone has disadvantage and forager can't even roll for it

![image](https://user-images.githubusercontent.com/77355668/126082843-3345e96e-c687-49fa-a5af-9c9947e3b6a5.png)

**Comment by subatoiWolf** [comment]
being able to use this DD dm screen would be invaluable!!! I am also running into the same issues and im using Forge if that matters.  Maybe the module needs some tweeking to work on Forge? Anyway thank you for the work you put into these modules

**Comment by Handyfon** [comment]
The darkscreen will be temporarily disabled until the next foundry version (v9)
