### ISSUE TITLE
DnD 5e 1.4.x

### ISSUE THREAD

**Issue by 20lbsOfBees** [Handyfon/Darksheet#34]
Since the recent update to the DnD 5e system, I have been unable to open some of my character sheets. "Find the Culprit" points to this module. Will you please update for the DnD 5e 1.4.x at your earliest convenience? Love this sheet and would appreciate being able to use it again.

**Comment by MMammoser** [comment]
FYI for Handy (and anyone else who runs into it) it seems to be caused by tool proficiencies. Having any of them enabled with cause the character sheet to be un-openable. Switching to another Character sheet and disabling them will let you open it again.
